Product_Locator/Locator/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



app_name = 'Locator'


urlpatterns = [
    path('', views.loc_input_view, name='loc_input'),
    path('find/', views.search_view, name='search_input'),
    path('find/<slug:slug>/', views.search_view, name='search_input'),
    path('out/<int:shp_id>/', views.shop_loc_view, name='loc_out'),
    path('out/', views.shop_loc_view, name='loc_out'),
    path('details/<int:prod_id>/',views.details, name='det_view'),
    path('onlines/',views.onl_view, name='online_func'),
    #path('user/<int:shp_id>/', views.login_success_view, name='user_home'),
    #path('user/', views.login_success_view, name='user_home'),
    #path('editInfo/<int:shp_id>/', views.editInfo_view, name='edit_Info'),
    path('test/', views.search_2, name='testing'),
]


urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Product_Locator/Product_Locator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('homepage/', include('products.urls')),
    path('shop/', include('shopDB.urls')),
    path('locator/', include('Locator.urls')),
    path('online/', include('online.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Product_Locator/online/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



app_name = 'online'

urlpatterns = [
    path('', views.add_Disc, name='add_disc'),

]


urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Product_Locator/shopDB/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



app_name = 'shopDB'


urlpatterns = [
    path('', views.login_view_s, name='login_shop'),
    path('add_disc/', views.add_Disc, name='discAdder'),
    path('user/<int:shp_id>/', views.login_success_view, name='user_home'),
    path('user/', views.login_success_view, name='user_home'),
    path('signup/', views.signup_view, name='user_regs'),
    path('editInfo/<int:shp_id>/', views.editInfo_view, name='edit_Info'),
    path('editInfo/', views.editInfo_view, name='edit_Info'),
    path('shop_products/<int:shp_id>/', views.All_products_view, name='shop_products'),
    path('shop_products/', views.All_products_view, name='shop_products'),
    ##path('shop_products/<slug:slug>', views.All_products_view, name='shop_products'),
    path('Add_Products/<int:shp_id>/', views.addProduct_view, name='add_products'),
    path('Add_Products/', views.addProduct_view, name='add_products'),
    path('Edit_Product/<slug:slug>/<int:shp_id>/', views.editProduct_view, name='edit_products'),
    path('Edit_Product/', views.editProduct_view, name='edit_products'),
    path('Sell_Product/<slug:slug>/<int:shp_id>/', views.sellProduct_view, name='sell_products'),
    path('Sell_Product/', views.sellProduct_view, name='sell_products'),
    path('sells_Log/<int:shp_id>/', views.sellsLog_view, name='sells_logs'),
    path('sells_Log/', views.sellsLog_view, name='sells_logs'),
    path('logout/<int:shp_id>/', views.logout_view, name='shop_logout'),
    path('shop_products/<slug:slug>/<int:shp_id>/',views.product_detail , name ="details"),

]


urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Product_Locator/online/models.py
from django.db import models

# Create your models here.

Product_Locator/online/views.py
from django.shortcuts import render, redirect
from shopDB.models import Discount
from django.contrib import messages

# Create your views here.
def add_Disc(request):
    if request.method == 'POST':
        print('YES')
        percen = request.POST.get('percentage')
        max_amount = request.POST.get('mx_amnt')
        diamount = request.POST.get('disc_amnt')

        if percen == "":
            perc = None
        else :
            perc = float(percen)

        if max_amount == "":
            max_amnt = None
        else :
            max_amnt = int(max_amount)

        if diamount == "":
            diamnt = None
        else :
            diamnt = float(diamount)

        new_disc = Discount(Percentage=perc, DiscountAmount=diamnt, MaxAmount=max_amnt)
        new_disc.save()
        messages.success(request, "Discount Added", )
        return render(request, 'Discount_add_pop.html')

    return render(request, 'Discount_add_pop.html')

Product_Locator/shopDB/views.py
# import here.
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product, Shop, Log, User, Discount
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.contrib import messages
from django.conf import settings
from django.core.files.storage import FileSystemStorage

#added by shawon for session
from django.contrib.auth.decorators import login_required

# Create your views here.

def All_products_view(request, shp_id=6):
    try:
        shop = Shop.objects.get(ShopID=shp_id)#if get function doesn't get a single object, it raises exception
    except:
        return render(request, 'noShop_error.html')
    user = User.objects.get(user=shop)
    if user.status != 'active': #user is idle, not logged in
        print(user)
        return render(request, 'error.html')
    #clear to go
    products = Product.objects.all().filter(shop=shop).order_by('ProductID') #gets all the products of the certain shop
    return render(request, 'products_list.html', {'products_list': products, 'Shop': shop})


def sellsLog_view(request, shp_id=6):
    try:
        shop = Shop.objects.get(ShopID=shp_id)#if get function doesn't get a single object, it raises exception
    except:
        return render(request, 'noShop_error.html')
    user = User.objects.get(user=shop)
    if user.status != 'active':#user is idle, not logged in
        print('user is not logged in')
        return render(request, 'error.html')

    log = Log.objects.all().filter(shop=shop) #gets all the logs of the certain shop
    return render(request, 'sells_log.html', {'logs': log, 'Shop': shop})


def editInfo_view(request, shp_id=6):

    if request.method=='POST':
        use_id = request.POST.get('id_use')
        try:
            shop = Shop.objects.get(ShopID=use_id)#if get function doesn't get a single object, it raises exception
        except:
            return render(request, 'noShop_error.html')
        user = User.objects.get(user=shop)
        if user.status != 'active':#user is idle, not logged in
            print('user is not logged in')
            return render(request, 'error.html')
        shpname = request.POST.get('shop_name')
        loc = request.POST.get('shop_location')
        prop = request.POST.get('user_name')
        mob = request.POST.get('shop_mobile')
        email = request.POST.get('shop_mail')
        latitude = request.POST.get('lati')
        longitude = request.POST.get('longi')

        #gets the shop and updates it
        up_shop = Shop.objects.get(ShopID=use_id)
        up_shop.ShopName = shpname
        up_shop.Location = loc
        up_shop.ContactNumber = mob
        up_shop.Email = email
        up_shop.UserName = prop
        up_shop.Longitude = longitude
        up_shop.Latitude = latitude
        up_shop.save() #saves the shop after updating
        #slug = use_id
        #up_user.update(name=uname, address=add, birthyear=b_yr, mobile_number=mob, email_id=email, profession=proff, bkash_account_no=bkash_acc)
        messages.success(request, "Changes saved", )
        return redirect('shopDB:edit_Info', shp_id=use_id )

    try:
        shop = Shop.objects.get(ShopID=shp_id)#if get function doesn't get a single object, it raises exception
    except:
        return render(request, 'noShop_error.html')
    user = User.objects.get(user=shop)
    if user.status != 'active':#user is idle, not logged in
        print('user is not logged in')
        return render(request, 'error.html')
    #shp = Shop.objects.get(ShopID=shp_id)
    print (shop.ShopName)
    return render(request, 'Edit_Profile.html', {'Shop': shop})




def add_Disc(request):
    if request.method == 'POST':
        perc = request.POST.get('percentage')
        max_amnt = request.POST.get('mx_amnt')
        diamnt = request.POST.get('disc_amnt')
        print(perc, diamnt)
        #all data are received
        if perc is None or perc=="":
            print('perc is null')
            if diamnt is None or diamnt=="":
                print(max_amnt)
                print('Null Entered')
                messages.success(request, "Discount not Added, No value entered", )
                #if no value is entered, discount isn't saved and redirected to actual page
                return render(request, 'Discount_add_pop.html')
        new_disc = Discount(Percentage=perc, DiscountAmount=diamnt, MaxAmount=max_amnt)
        new_disc.save()
        messages.success(request, "Discount Added", ) #Discount added and will be redirected to pop up page
        return render(request, 'Discount_add_pop.html')

    return render(request, 'Discount_add_pop.html')




def addProduct_view(request, shp_id=6):
    if request.method == 'POST':
        shops_id = request.POST.get('shops_idd')
        try:
            shop = Shop.objects.get(ShopID=shops_id)#if get function doesn't get a single object, it raises exception
        except:
            return render(request, 'noShop_error.html')
        user = User.objects.get(user=shop)
        if user.status != 'active':
            print('user is not logged in')
            return render(request, 'error.html')
        name = request.POST.get('product_name')
        pri = request.POST.get('product_sell_price')
        cst = request.POST.get('product_cost')
        qtt = request.POST.get('available_quantity')
        disc = request.POST.get('percentage_discount')
        mfg = request.POST.get('prod_mfg')
        exp = request.POST.get('prod_exp')
        #if date are not entered, it'll be set to none
        if exp == "":
            exp = None
        if mfg =="":
            mfg = None

        if len(request.FILES) != 0: #check if photo was uploaded
            print('photo chosen')
            photo = request.FILES['filebutton']
        else:#if not uploaded, set photo to none
            print('No photo chosen')
            photo = None

        shp=Shop.objects.get(ShopID=shops_id)
        discount = Discount.objects.get(DiscountID=disc) #while saving we need whole discount model, not just id
        print (name,pri,cst, shp_id)
        try:
            all_shop_prods = Product.objects.all().filter(shop=shp)#if get function doesn't get a single object, it raises exception
            prod = all_shop_prods.get(ProductName=name)
            print(prod)
        #print(type(prod))
        #if type(prod) is set or type(prod) is list :
        except: #exception means the set is empty and there is not same named product as this one... So, good to save
            new_prod = Product(ProductName=name, BuyingPrice=cst, SellingPrice=pri, image=photo, shop=shp, Quantity=qtt,
                               discount=discount, Mfg=mfg, Exp=exp)
            new_prod.save()
            messages.success(request, "Product Added", )
            print(shops_id)
            return redirect('shopDB:add_products', shp_id=shops_id)

        #No exception means set isn't empty and there is already a product
        print('Already Exists')
        messages.success(request, "Product not Added, Already Exists", )
        return redirect('shopDB:add_products', shp_id=shops_id)

    try:
        shop = Shop.objects.get(ShopID=shp_id)#if get function doesn't get a single object, it raises exception
    except:
        return render(request, 'noShop_error.html')
    user = User.objects.get(user=shop)
    if user.status != 'active':
        print('user is not logged in')
        return render(request, 'error.html')
    #shp = Shop.objects.get(ShopID=shp_id)
    discs = Discount.objects.all().order_by('Percentage') #For dropdown list of Discount
    return render(request, 'product_Add.html', {'Shop': shop, 'discounts':discs})




def editProduct_view(request, slug='abcd', shp_id=6):

    if request.method=='POST':
        shops_id = request.POST.get('shops_idd')
        try:
            shop = Shop.objects.get(ShopID=shops_id)#if get function doesn't get a single object, it raises exception
        except:
            return render(request, 'noShop_error.html')
        user = User.objects.get(user=shop)
        if user.status != 'active':
            print('user is not logged in')
            return render(request, 'error.html')
        prod_id = request.POST.get('product_id')
        prod_name = request.POST.get('product_name')
        cst = request.POST.get('product_cost')
        quan = request.POST.get('available_quantity')
        pro_pri = request.POST.get('product_sell_price')
        disc = request.POST.get('percentage_discount')
        mfg = request.POST.get('prod_mfg')
        exp = request.POST.get('prod_exp')
        #Got all the data
        discunt = Discount.objects.get(DiscountID=disc)

        #now get the product from database
        up_prod = Product.objects.get(ProductID=prod_id)
        up_prod.ProductName = prod_name
        up_prod.SellingPrice = pro_pri
        up_prod.BuyingPrice = cst
        up_prod.Quantity = quan
        up_prod.discount = discunt
        #dates will be updated only if it was changed
        if mfg != "":
            up_prod.Mfg = mfg
        if exp != "":
            up_prod.Exp = exp
        #check if the photo was uploaded
        if len(request.FILES) != 0:
            print('photo chosen')
            photo = request.FILES['filebutton']
            up_prod.image = photo
        up_prod.save() #saved after updating
        #slug = use_id
        #up_user.update(name=uname, address=add, birthyear=b_yr, mobile_number=mob, email_id=email, profession=proff, bkash_account_no=bkash_acc)
        messages.success(request, "Changes saved", )
        return redirect('shopDB:edit_products', slug=prod_name, shp_id=shops_id )

    try:
        shop = Shop.objects.get(ShopID=shp_id)#if get function doesn't get a single object, it raises exception
    except:
        return render(request, 'noShop_error.html')
    user = User.objects.get(user=shop)
    if user.status != 'active':

Product_Locator/shopDB/templates/Product_Details_new_old.html
<!DOCTYPE html>

<html>

<!-- {%load staticfiles %} -->
{% load static from staticfiles %}

<head>


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">


<!--
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
-->

<link href="{% static '/shop_db/css/bootstrap_4.css' %}" rel="stylesheet" id="bootstrap-css">
<link href="{% static '/shop_db/css/shop_user_profile_up.css' %}" rel="stylesheet" id="shop_user">
<script src="{% static '/shop_db/js/bootstrap_4.js' %}"></script>
<script src="{% static '/shop_db/js/jquery3_2_1.js' %}"></script>
<!------ Include the above in your HEAD tag ---------->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<style>
	.product_view{
		max-width: 800px; 
		width: 100%;
	} 
	.modal-dialog{
		max-width: 800px; 
		width: 100%;
	}

    .pre-cost{
		text-decoration: line-through; 
		color: #a5a5a5;
	}
    .space-ten{
		padding: 10px 0;
	}
		
</style>


</head>


<body>
    <div class="container main-secction all">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 image-section" >
				<!-- Top image ********************************************** -->
                <!-- img src="https://png.pngtree.com/thumb_back/fw800/back_pic/00/08/57/41562ad4a92b16a.jpg"-->
				<img src="{% static '/shop_db/img/header.jpg' %}">
            </div>

            <div class="row user-left-part">

                <div class="col-md-3 col-sm-3 col-xs-3 user-profil-part pull-left">
                    <!--div class="row "-->

                        <div class="col-md-12 col-md-12-sm-12 col-xs-12 user-image text-center">
						<!-- profile image ********************************************
                            <img src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png" class="rounded-circle">
                            --->
                        </div>

                        <div class="col-md-12 col-sm-12 col-xs-12 user-detail-section1 text-center">
							<!-- options under profile pics -->
                            <a href="{% url 'shopDB:user_home' shp_id=Shop.ShopID %}" class="btn btn-success btn-block follow">Home</a>
                            <a href="{% url 'shopDB:edit_Info' shp_id=Shop.ShopID  %}" class="btn btn-success btn-block follow">Edit Info</a>
                            <a href="{% url 'shopDB:shop_products'  shp_id=Shop.ShopID %}" class="btn btn-success btn-block follow">View All Products</a>
                            <a href="{% url 'shopDB:add_products' shp_id=Shop.ShopID%}" class="btn btn-success btn-block follow">Add Product</a>
                            <a href="{% url 'shopDB:sells_logs' shp_id=Shop.ShopID%}" class="btn btn-success btn-block follow">Sales Log</a>
                            <a href="{% url 'shopDB:shop_logout' shp_id=Shop.ShopID %}" class="btn btn-primary btn-block">Log Out</a>
							<!--
							<a href="/search" class="btn btn-primary btn-block">View All Products</a>
							-->
                        <!--/div-->

                    </div>
                </div>

				
				
				<div class="col-md-9 col-sm-9 col-xs-12 pull-right">
					<!-- write your codes here -->
					{% block content %}
					
					<div class="container">
						<div class="row">
							<div class="col-md-6">
								  <div class="thumbnail">
						<div class="space-ten"></div><div class="space-ten"></div>
					<!--	<img src="http://tech.firstpost.com/wp-content/uploads/2014/09/Apple_iPhone6_Reuters.jpg" alt="" class="img-responsive"> -->
									{% if product.image %}
									<a href="{% url 'shopDB:details' slug=Product.ProductName shp_id=Shop.ShopID %}">
									<img src="{{ Product.image.url}}" alt={{Product.ProductName}} class="img-responsive">
									</a>
									{% else %}
								   <h1 align="center" style="color:red">No image available</h1>
									{% endif %}
									<div class="caption">
									  <h4 class="pull-right"><span>&#2547;</span> {{Product.SellingPrice}}</h4>
									  <h4 style="color:blue">{{Product.ProductName}}</h4>
									  <p>{{product.description}}Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
									</div>
									<!--div class="ratings">
									  <p>
										<span class="glyphicon glyphicon-star"></span>
										<span class="glyphicon glyphicon-star"></span>
										<span class="glyphicon glyphicon-star"></span>
										<span class="glyphicon glyphicon-star"></span>
										<span class="glyphicon glyphicon-star"></span>
										 (15 reviews)
									  </p>
									</div>
									<div class="space-ten"></div-->
									<div class="btn-ground text-center">
										
										<a href="{% url 'shopDB:edit_products' slug=Product.ProductName shp_id=Shop.ShopID %}" class=" btn btn-primary btn-block follow">Edit Product</a>
										<a href="{% url 'shopDB:sell_products' slug=Product.ProductName shp_id=Shop.ShopID %}" class=" btn btn-primary btn-block follow">Sell Product</a>
									</div>
									<div class="space-ten"></div>
								  </div>
								</div>
								<div class="space-ten"></div>
								  </div>
								</div>
							</div>
						</div>


					{% endblock %}
					<!-- till here ---->
				</div>
				
				
				
            </div>
        </div>
    </div>


	
	<!-- 
	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	-->
	
</body>
</html>

Product_Locator/shopDB/templates/error.html
<html>
<head>
    <title>Error Page</title>
    <style>
        .par {
            position:absolute;
            top:150px;
            left:35%;
        }
    </style>
</head>
<body>

    <p class="par" align="center">
		<b><font size="10" style="color:#331a00">You are not Logged in</font></b>
	<br /><br /><br />
		<a href="{% url 'shopDB:login_shop' %}"><font size="6" style="color:#000099" >Login >></font></a>
	</p>
</body>
</html>

Product_Locator/shopDB/templates/login_new.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static from staticfiles %}
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static '/shop_db/css/login_style.css' %}">
  </head>
  <body>
  
	
  
<div class="login-box">
  <h1>Login</h1>

  <form action="/shop/" method="POST">
    {% csrf_token %}

    <div class="textbox">
      <i class="fas fa-user"></i>
      <input type="text" placeholder="Username" name="username" required>
    </div>

    <div class="textbox">
      <i class="fas fa-lock"></i>
      <input type="password" placeholder="Password" name="psw" required>
    </div>

    <button type="submit" class="btn">Sign in</button>

  </form>
  <div class="login-register" align="center">
		<p style="color:white"> Don't have a account? </p><a href="{% url 'shopDB:user_regs' %}"><p style="color:white"><b>SignUp</b></p></a>
	</div>
  
  
</div>
  </body>
</html>

Product_Locator/shopDB/templates/products_list.html
<!DOCTYPE html>

<html>

<!-- {%load staticfiles %} -->
{% load static from staticfiles %}

<head>


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">


<!--
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
-->

<link href="{% static '/shop_db/css/bootstrap_4.css' %}" rel="stylesheet" id="bootstrap-css">
<link href="{% static '/shop_db/css/shop_user_profile_up.css' %}" rel="stylesheet" id="shop_user">
<script src="{% static '/shop_db/js/bootstrap_4.js' %}"></script>
<script src="{% static '/shop_db/js/jquery3_2_1.js' %}"></script>
<!------ Include the above in your HEAD tag ---------->





</head>


<body>
    <div class="container main-secction all">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 image-section">
				<!-- Top image ********************************************** -->
				<img src="{% static '/shop_db/img/header.jpg' %}">
            </div>

            <div class="row user-left-part">

                <div class="col-md-3 col-sm-3 col-xs-3 user-profil-part pull-left">
                    <!--div class="row "-->

                        <div class="col-md-12 col-md-12-sm-12 col-xs-12 user-image text-center">
						<!-- profile image ********************************************
                            <img src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png" class="rounded-circle">
                            --->
                        </div>

                        <div class="col-md-12 col-sm-12 col-xs-12 user-detail-section1 text-center">
							<!-- options under profile pics -->
                            <a href="{% url 'shopDB:user_home' shp_id=Shop.ShopID %}" class="btn btn-success btn-block follow">Home</a>
                            <a href="{% url 'shopDB:edit_Info' shp_id=Shop.ShopID  %}" class="btn btn-success btn-block follow">Edit Info</a>
                            <a href="{% url 'shopDB:shop_products'  shp_id=Shop.ShopID %}" class="btn btn-success btn-block follow">View All Products</a>
                            <a href="{% url 'shopDB:add_products' shp_id=Shop.ShopID%}" class="btn btn-success btn-block follow">Add Product</a>
                            <a href="{% url 'shopDB:sells_logs' shp_id=Shop.ShopID%}" class="btn btn-success btn-block follow">Sales Log</a>
                            <a href="{% url 'shopDB:shop_logout' shp_id=Shop.ShopID %}" class="btn btn-primary btn-block">Log Out</a>
							<!--
							<a href="/search" class="btn btn-primary btn-block">View All Products</a>
							-->
                        <!--/div-->

                    </div>
                </div>



				<div class="col-md-9 col-sm-9 col-xs-12 pull-right">
					<!-- write your codes here
					{% block content %} -->


					<!--div  style="height:10px"></div-->

						<link href="{% static '/shop_db/css/bootstrap_3_3_0.css' %}" rel="stylesheet" id="bootstrap-css2">
						<script src="{% static '/shop_db/js/bootstrap_3_3_0.js' %}"></script>
						<script src="{% static '/shop_db/js/jquery1_11.js' %}"></script>

						<!--
						<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
						<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
						<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
						-->
						<!------ Include the above in your HEAD tag ---------->





						<div class="container" style="padding-top: 10px;">
							<!--h4 style="color:blue" align="center">{{product.shop.ShopName}}</h4-->
						  <h1 class="page-header" style="color:blue" align="left"><b>All available products</b></h1>
						  <div class="row">
							<!-- left column --
							<div class="col-md-3 col-sm-6 col-xs-12">
							  <div class="text-center">
								<img src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png" class="avatar img-circle img-thumbnail" alt="avatar">
								<h6>Change Profile Picture...</h6>
								<input type="file" class="text-center center-block well well-sm">		<!-- Image Input Here --
							  </div>
							</div>
                            -->
							<!-- edit form column -->
							<div class="col-md-9 col-sm-6 col-xs-12 personal-info">
								<div class="panel panel-primary">
									<div class="panel-heading">
										<h3 align = center>List of products
											<!--
											<div class="pull-right">
												<button id="btn-admin" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> Edit</button>
											</div>
											-->
										</h3>
									</div>


									<table class="table table-striped table-hover">
										<thead>
											<tr>
												<th>Product ID </th>
												<th>Product Name</th>
												<th>Selling Price</th>
											</tr>
										</thead>

												<!-- <th>Available</th> -->

										{% for product in products_list %}
										<tbody>
											<tr class="success">
												<td> {{product.ProductID}} </td>
												<td><a href="{% url 'shopDB:details' slug=product.ProductName shp_id=Shop.ShopID %}"><p ><font size="5px"> {{product.ProductName}} <font></p></a></td>
												<td> <p><font size="3px"> <span>&#2547;</span>  {{product.SellingPrice}} </font></p> </td>
												<!-- <td> {{product.quantity}} </td>  -->
											</tr>
										</tbody>
										
										{% endfor %}
									</table>
								</div>
								
							</div>
						  </div>
						</div>

					<!-- {% endblock %}
					till here ---->
				</div>



            </div>
        </div>
    </div>



	<!--
	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	-->
	
</body>
</html>